import math

SECS_MIN = lambda MIN: 60.0 * MIN
SECS_HOUR = lambda HOUR: 3600.0 * HOUR
SECS_DAY = lambda DAY: 3600.0 * 24.0 * DAY
INF = 1e16
PASS = "PASS"
FAIL = "FAIL"

AUTO_ID = "##_AUTO_GENERATE_##"

TRACKER_DEFAULT_INTERVAL = SECS_MIN(5)
TRACKER_DEFAULT_OLDEST_EPOCH = SECS_DAY(30)

DEFAULT_NEXT_BOX_PROBABILITY = 1.0 - 0.8

STATE_STUDYING = "STUDYING"
STATE_NEW = "NEW"
STATE_STUDIED = "STUDIED"

INVALID_DURATION = -1

DEFAULT_BOX_TRANSFORMATION = lambda at_time, box: box + 1.0 * math.exp(-at_time)

LABEL_COMPETENCY = "competency"
LABEL_TAG = "tag"
LABEL_STATE = "state"
LABEL_PASS = "pass"
EXTRA_INFO = [LABEL_TAG, LABEL_STATE, LABEL_COMPETENCY, LABEL_PASS]

