#!/bin/sh

item="$(echo -e "$(python ../main.py --subject leetcode -c list --states studying)" | fzf --ansi)"

if [[ "$item" == "" ]]
then
	echo "Nothing to cancel"
	exit 0
fi

identifier="$(echo "$item" | awk -F ']' '{print $1}' | sed 's/[^[:alnum:]]//g')"
name="$(echo "$item" | awk -F ']' '{print $2}' | awk -F "\"" '{print $2}' | sed 's/[^[:alnum:]-]//g')"

yesno="$(echo -e "yes\nno" | fzf --prompt "Cancel? ")"

if [[ "$item" != "" && "$yesno" == "yes" ]]
then
	echo "Cancel studying $identifier. $name"
 	python ../main.py --subject leetcode -c cancel -i "$identifier"
fi

