#!/bin/sh

tag="$(echo -e "$(python ../main.py --subject leetcode -c list_tag --states studying)" | fzf | awk -F ':' '{print $1}')"
if [[ "$tag" == "" ]]
then
	echo "Nothing to cancel"
	exit 0
fi

item="$(echo -e "$(python ../main.py --subject leetcode -c list --tags "$tag" --states studying)" | fzf --ansi)"

identifier="$(echo "$item" | awk -F ']' '{print $1}' | sed 's/[^[:alnum:]]//g')"
name="$(echo "$item" | awk -F ']' '{print $2}' | awk '{print $1}' | sed 's/[^[:alnum:]-]//g')"

passfail="$(echo -e "pass\nfail" | fzf)"

if [ "$item" != "" ]
then
	python ../main.py --subject leetcode -c end -i "$identifier" --passfail $passfail
fi

