#!/bin/sh

if [ "$#" = 0 ]
then
	echo "Require tags"
	exit
fi

item="$(echo -e "$(python ../main.py --subject leetcode -c list --by recent --direction inc)" | fzf --ansi)"

identifier="$(echo "$item" | awk -F ']' '{print $1}' | sed 's/[^[:alnum:]]//g')"
name="$(echo "$item" | awk -F ']' '{print $2}' | awk -F "\"" '{print $2}' | sed 's/[^[:alnum:]-]//g')"

if [ "$item" != "" ]
then
	echo "Remove tags: $1 to: $identifier. $name"
	python ../main.py --subject leetcode -c remove_tag -i "$identifier" --tags "$1"
fi

