#!/bin/sh

tag="$(echo -e "$(python ../main.py --subject leetcode -c list_tag)" | fzf | awk -F ':' '{print $1}')"
item="$(echo -e "$(python ../main.py --subject leetcode -c list --tags "$tag")" | fzf --ansi)"

identifier="$(echo "$item" | awk -F ']' '{print $1}' | sed 's/[^[:alnum:]]//g')"
name="$(echo "$item" | awk -F ']' '{print $2}' | awk '{print $1}' | sed 's/[^[:alnum:]-]//g')"

if [ "$item" != "" ]
then
	PATHTOCODE="$(python ../main.py --subject leetcode -c get_file -i "$identifier" --postfix "code.py")"

	python ../main.py --subject leetcode -c start -i "$identifier" && echo "Start $identifier. $name" && neovide "$PATHTOCODE"
fi

