#!/bin/sh

probleminfo="$(cat "problem-lists.txt" | fzf)"

ID="$(echo -e "$probleminfo" | awk '{print $1}')"
PROBLEM="$(echo -e "$probleminfo" | awk '{print $2}')"
TAGS="$(echo -e "$probleminfo" | awk '{print $3}')"

if [ "$PROBLEM" != "" ]
then
	echo "Add $ID ($PROBLEM)"
	python ../main.py --subject leetcode -c add --identifier $ID --name $PROBLEM --tags $TAGS
fi

