#!/usr/bin/sh
# (1) browse the list of added problems and add a tag
#   ./vy-add-tag -t {tags_separated_by_comma}
# (2) add a tag to a problem with problem_id
#   ./vy-add-tag -i {problem_id} -t {tags_separated_by_comma}

BASEDIR=$(dirname "$0")
. "${BASEDIR}"/vy-config

IDENTIFIER=""
TAGS=""

while getopts ":i:t:" opt; do
  case $opt in
    i) IDENTIFIER="$OPTARG"
    ;;
    t) TAGS="$OPTARG"
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    exit 1
    ;;
  esac
done

if [ "$TAGS" = "" ]
then
	ALL_TAGS="$(python ../main.py --subject $SUBJECT -c list_state_by_tag --states new,studied,studying)"
	TAGS="$(echo -e "$ALL_TAGS" | fzf --ansi --prompt "Select a tag to add: " | awk -F ':' '{ print $1 }' | xargs)"

	if [ "$TAGS" == "" ]
	then
		read -p "Please enter a new tag: " TAGS
		if [ "$TAGS" == "" ]
		then
			printf "No tag is provided. Exit."
			exit 1
		fi
	fi
fi

if [ "$IDENTIFIER" != "" ]
then
	NAME="$(python ../main.py --subject "$SUBJECT" -c get_name -i "$IDENTIFIER")"

	if [ "$NAME" = "##_not_exist_##" ]
	then
		echo "$IDENTIFIER does not exist!"
		exit 1
	fi

	yesno="$(printf "yes\nno" \
		     | fzf --cycle --ansi --prompt "Add tags $TAGS to $IDENTIFIER ($NAME)? ")"

	if [ "$yesno" = "yes" ]
	then
		echo "Add tags: $TAGS to: $IDENTIFIER ($NAME)"
		python ../main.py --subject "$SUBJECT" -c add_tag -i "$IDENTIFIER" --tags "$TAGS"
	fi

	exit 0
fi

ITEM="$(printf "%s" "$(python ../main.py \
	                          --subject "$SUBJECT" \
							  -c list \
							  --by recent \
							  --direction dec)" \
	    | fzf --cycle --ansi)"

IDENTIFIER="$(echo "$ITEM" | awk -F ']' '{print $1}' | sed 's/[^[:alnum:]]//g')"
NAME="$(echo "$ITEM" \
	    | awk -F ']' '{print $2}' \
		| awk -F "\"" '{print $2}' \
		| sed 's/[^[:alnum:]-]//g')"

yesno="$(printf "yes\nno" \
		 | fzf --cycle --ansi --prompt "Add tags $TAGS to $IDENTIFIER ($NAME)? ")"

if [ "$yesno" = "yes" ]
then
	echo "Add tags: $TAGS to: $IDENTIFIER ($NAME)"
	python ../main.py --subject "$SUBJECT" -c add_tag -i "$IDENTIFIER" --tags "$TAGS"
fi

