#!/bin/sh

BASEDIR=$(dirname $0)
source "${BASEDIR}"/vy-config

if [ "$#" = 0 ]
then
	echo "Require tags"
	exit
fi

ITEM="$(echo -e "$(python ../main.py --subject $SUBJECT -c list --by recent --direction dec)" | fzf --ansi)"

IDENTIFIER="$(echo "$ITEM" | awk -F ']' '{print $1}' | sed 's/[^[:alnum:]]//g')"
NAME="$(echo "$ITEM" | awk -F ']' '{print $2}' | awk -F "\"" '{print $2}' | sed 's/[^[:alnum:]-]//g')"

if [ "$ITEM" != "" ]
then
	echo "Add tags: $1 to: $IDENTIFIER ($NAME)"
	python ../main.py --subject $SUBJECT -c add_tag -i "$IDENTIFIER" --tags "$1"
fi

