#!/bin/sh

BASEDIR=$(dirname $0)
source "${BASEDIR}"/vy-config

ITEM="$(echo -e "$(python ../main.py --subject $SUBJECT -c list --states studying)" | fzf --cycle --ansi)"

if [[ "$ITEM" == "" ]]
then
	echo "Nothing to cancel"
	exit 0
fi

IDENTIFIER="$(echo "$ITEM" | awk -F ']' '{print $1}' | sed 's/[^[:alnum:]]//g')"
NAME="$(echo "$ITEM" | awk -F ']' '{print $2}' | awk -F "\"" '{print $2}' | sed 's/[^[:alnum:]-]//g')"

yesno="$(echo -e "yes\nno" | fzf --cycle --ansi --prompt "Cancel studying $IDENTIFIER ($NAME)? ")"

if [[ "$ITEM" != "" && "$yesno" == "yes" ]]
then
	echo "Cancel studying $IDENTIFIER ($NAME)"
 	python ../main.py --subject $SUBJECT -c cancel -i "$IDENTIFIER"
fi

