#!/usr/bin/sh
# set the state of a _studying_ problem to studied
# with a result pass or fail
#  ./vy-complete

BASEDIR=$(dirname "$0")
. "${BASEDIR}"/vy-config

ITEM="$(printf "%s" "$(python "${BASEDIR}"/../main.py --subject "$SUBJECT" \
                                         -c list \
										 --states studying)" \
			           | fzf --cycle --ansi)"

IDENTIFIER="$(printf "%s" "$ITEM" \
	          | awk -F ']' '{print $1}' \
			  | sed 's/[^[:alnum:]]//g')"
NAME="$(printf "%s" "$ITEM" \
	    | awk -F ']' '{print $2}' \
		| awk -F "\"" '{print $2}' \
		| sed 's/[^[:alnum:]-]//g')"

if [ "$ITEM" != "" ]
then
	passfail="$(printf "pass\nfail" | fzf --cycle --ansi)"
	if [ "$passfail" != "" ]
	then
		printf "%s %s (%s)" "$passfail" "$IDENTIFIER" "$NAME"
		python "${BASEDIR}"/../main.py --subject "$SUBJECT" \
		                  -c end \
						  -i "$IDENTIFIER" \
						  --passfail "$passfail"
	fi
fi

