#!/usr/bin/sh
# create leetcode subject in case it does not exist
#   by creating the following directories
#     ../subjects/sbj-leetcode/
#     ../subjects/sbj-leetcode/item/
#     ../subjects/sbj-leetcode/study/
#     ../subjects/sbj-leetcode/tracker/

BASEDIR=$(dirname "$0")
. "${BASEDIR}"/vy-config

python "${BASEDIR}"/../main.py --subject "$SUBJECT" -c add_subject

