#!/bin/bash
# states, tags, by, direction
TAGS="all"
BY="view"
DIRECTION="inc"

while getopts ":t:b:d:" opt; do
  case $opt in
    t) TAGS="$OPTARG"
    ;;
    b) BY="$OPTARG"
    ;;
    d) DIRECTION="$OPTARG"
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    exit 1
    ;;
  esac
done

echo -e "$(python ../main.py --subject leetcode -c list --states new --tags $TAGS --by $BY --direction $DIRECTION)" | fzf

