#!/bin/bash
# states, tags, by, direction
# default: list by number of studies, newest first
TAGS="all"

while getopts ":s:t:b:d:" opt; do
  case $opt in
    t) TAGS="$OPTARG"
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    exit 1
    ;;
  esac
done

echo -e "$(python ../main.py --subject leetcode -c list --states studied,studying --tags $TAGS --by view --direction inc)" | fzf

