#!/usr/bin/sh
# (1) list all added problems by number of views (least number of views first)
#   ./vy-list
# (2) list all add problems with a given states,
#              tags,
#              by some criterion,
#              and a direction (inc: increasing or dec:decreasing) of the criterion
#   ./vy-list -s {states_separated_by_comma}
#             -t {tags_separated_by_comma}
#             -b {criterion}
#             -d {direction}

BASEDIR=$(dirname "$0")
. "${BASEDIR}"/vy-config

STATES="all"
TAGS="all"
BY="recent"
DIRECTION="inc"

while getopts ":s:t:b:d:" opt; do
  case $opt in
    s) STATES="$OPTARG"
    ;;
    t) TAGS="$OPTARG"
    ;;
    b) BY="$OPTARG"
    ;;
    d) DIRECTION="$OPTARG"
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    exit 1
    ;;
  esac
done

printf "%s" "$(python ../main.py --subject "$SUBJECT" \
	                             -c list \
								 --states "$STATES" \
								 --tags "$TAGS" \
								 --by "$BY" \
								 --direction "$DIRECTION")" \
	   | fzf --cycle --ansi

