#!/bin/bash
# list problems based on how recently we solved them

BASEDIR=$(dirname $0)
source "${BASEDIR}"/vy-config

TAGS="all"

while getopts ":s:t:b:d:" opt; do
  case $opt in
    t) TAGS="$OPTARG"
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    exit 1
    ;;
  esac
done

echo -e "$(python ../main.py --subject $SUBJECT -c list --states studied,studying --tags $TAGS --by recent --direction inc)" | fzf --cycle --ansi

