#!/bin/bash
BASEDIR=$(dirname $0)
source "${BASEDIR}"/vy-config

TAGS="all"
BY="view"
DIRECTION="inc"

while getopts ":s:t:b:d:" opt; do
  case $opt in
    t) TAGS="$OPTARG"
    ;;
    b) BY="$OPTARG"
    ;;
    d) DIRECTION="$OPTARG"
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    exit 1
    ;;
  esac
done

echo -e "$(python ../main.py --subject $SUBJECT -c list --states studying --tags $TAGS --by $BY --direction $DIRECTION)" | fzf --cycle --ansi

