#!/bin/bash
# list problems based on the number of times we successfully solved them
BASEDIR=$(dirname $0)
source "${BASEDIR}"/vy-config

STATES="studied,studying"
TAGS="all"
BY="pass"
DIRECTION="inc"

while getopts ":s:t:b:d:" opt; do
  case $opt in
    t) TAGS="$OPTARG"
    ;;
    d) DIRECTION="$OPTARG"
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    exit 1
    ;;
  esac
done

echo -e "$(python ../main.py --subject $SUBJECT -c list --states $STATES --tags $TAGS --by $BY --direction $DIRECTION)" | fzf --ansi

