#!/bin/bash
# list problems based on how recently we solved them
TAGS="all"

while getopts ":s:t:b:d:" opt; do
  case $opt in
    t) TAGS="$OPTARG"
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    exit 1
    ;;
  esac
done

echo -e "$(python ../main.py --subject leetcode -c list --states studied,studying --tags $TAGS --by recent --direction inc)" | fzf --ansi

