#!/bin/bash
# states, tags, by, direction
# default: list by number of studies, newest first
STATES="studied,studying"
TAGS="all"
BY="duration"
DIRECTION="dec"

while getopts ":s:t:b:d:" opt; do
  case $opt in
    t) TAGS="$OPTARG"
    ;;
    d) DIRECTION="$OPTARG"
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    exit 1
    ;;
  esac
done

echo -e "$(python ../main.py --subject leetcode -c list --states $STATES --tags $TAGS --by $BY --direction $DIRECTION)" | fzf

