#!/bin/sh

item="$(echo -e "$(python ../main.py --subject leetcode -c list --by recent --direction inc)" | fzf --ansi)"

identifier="$(echo "$item" | awk -F ']' '{print $1}' | sed 's/[^[:alnum:]]//g')"
name="$(echo "$item" | awk -F ']' '{print $2}' | awk -F "\"" '{print $2}' | sed 's/[^[:alnum:]-]//g')"

if [ "$item" != "" ]
then
	PATHTONOTE="$(python ../main.py --subject leetcode -c get_file -i "$identifier" --postfix "node.md")"

	echo "# $identifier. $name" >> $PATHTONOTE \
		&& echo "Note for $identifier. $name at $PATHTONOTE" \
		&& neovide "$PATHTONOTE"
fi

