#!/bin/sh
BASEDIR=$(dirname $0)
source "${BASEDIR}"/vy-config

IDENTIFIER=""

while getopts ":i:" opt; do
  case $opt in
    i) IDENTIFIER="$OPTARG"
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    exit 1
    ;;
  esac
done


if [ "$IDENTIFIER" != "" ]
then
	NAME="$(python "${BASEDIR}"/../main.py --subject $SUBJECT -c get_name -i "$IDENTIFIER")"
	if [[ "$NAME" == "##_not_exist_##" ]]
	then
		echo "$IDENTIFIER does not exist!"
		exit 1
	fi

	yesno="$(echo -e "yes\nno" | fzf --cycle --ansi --prompt "Add notes to $IDENTIFIER($NAME)? ")"

	if [[ "$yesno" == "yes" ]]
	then
		PATHTONOTE="$(python "${BASEDIR}"/../main.py --subject $SUBJECT -c get_file -i "$IDENTIFIER" --postfix "notes.md")"

		echo "Note for $IDENTIFIER ($NAME) at $PATHTONOTE" \
			&& $EDITOR "$PATHTONOTE"
	fi

	exit 0
fi



ITEM="$(echo -e "$(python "${BASEDIR}"/../main.py --subject $SUBJECT -c list --by recent --direction inc)" | fzf --ansi)"

IDENTIFIER="$(echo "$ITEM" | awk -F ']' '{print $1}' | sed 's/[^[:alnum:]]//g')"
NAME="$(echo "$ITEM" | awk -F ']' '{print $2}' | awk -F "\"" '{print $2}' | sed 's/[^[:alnum:]-]//g')"

if [ "$ITEM" != "" ]
then
	PATHTONOTE="$(python "${BASEDIR}"/../main.py --subject $SUBJECT -c get_file -i "$IDENTIFIER" --postfix "notes.md")"

	echo "Note for $IDENTIFIER ($NAME) at $PATHTONOTE" \
		&& $EDITOR "$PATHTONOTE"
fi

