#!/bin/bash
BASEDIR=$(dirname $0)
source "${BASEDIR}"/vy-config

IDENTIFIER=""

while getopts ":i:" opt; do
  case $opt in
    i) IDENTIFIER="$OPTARG"
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    exit 1
    ;;
  esac
done


if [ "$IDENTIFIER" != "" ]
then
	NAME="$(python ../main.py --subject $SUBJECT -c get_name -i "$IDENTIFIER")"

	if [[ "$NAME" == "##_not_exist_##" ]]
	then
		echo "Problem $IDENTIFIER does not exist!"
		exit 1
	fi

	yesno="$(echo -e "yes\nno" | fzf --cycle --ansi --prompt "Start to study $IDENTIFIER ($NAME)? ")"

	if [[ "$yesno" == "yes" ]]
	then
		PATHTOCODE="$(python ../main.py --subject $SUBJECT -c get_file -i "$IDENTIFIER" --postfix "code.py")"

		python ../main.py --subject $SUBJECT -c start -i "$IDENTIFIER" \
			&& echo "Start coding $IDENTIFIER ($NAME) at $PATHTOCODE" \
			&& $EDITOR "$PATHTOCODE"
	fi

	exit 0
fi


tag="$(echo -e "$(python ../main.py --subject $SUBJECT -c list_state_by_tag --states new,studied,studying)" | fzf --cycle --ansi | awk -F ':' '{print $1}')"

ITEM="$(echo -e "$(python ../main.py --subject $SUBJECT -c list --tags "$tag" --states new,studied,studying)" | fzf --cycle --ansi)"

IDENTIFIER="$(echo "$ITEM" | awk -F ']' '{print $1}' | sed 's/[^[:alnum:]]//g')"
NAME="$(echo "$ITEM" | awk -F ']' '{print $2}' | awk -F "\"" '{print $2}' | sed 's/[^[:alnum:]-]//g')"

if [ "$ITEM" != "" ]
then
	PATHTOCODE="$(python ../main.py --subject $SUBJECT -c get_file -i "$IDENTIFIER" --postfix "code.py")"

	python ../main.py --subject $SUBJECT -c start -i "$IDENTIFIER" \
		&& echo "Start coding $IDENTIFIER ($NAME) at $PATHTOCODE" \
		&& $EDITOR "$PATHTOCODE"
fi

